import { FoodItem } from '@/types/types';

export const SEED_DATA: FoodItem[] = [
  {
    id: 'seed-1',
    title: 'Lentils and Vegetable Stew',
    description: 'A hearty and simple stew with red lentils, carrots, celery, and spinach. Served with brown rice.',
    imageUri: '',
    tags: ['lentils', 'carrots', 'spinach', 'vegan', 'easy'],
    categories: ['Dinner'],
    createdAt: '2026-03-01T12:00:00.000Z',
  },
  {
    id: 'seed-2',
    title: 'Mushroom Risotto',
    description: 'Creamy arborio rice with mixed mushrooms, parmesan, and fresh thyme. A comforting Italian classic.',
    imageUri: '',
    tags: ['mushrooms', 'rice', 'parmesan', 'thyme'],
    categories: ['Dinner'],
    createdAt: '2026-03-01T11:00:00.000Z',
  },
  {
    id: 'seed-3',
    title: 'Kale Salad',
    description: 'Fresh kale with roasted chickpeas, avocado, cherry tomatoes, and lemon tahini dressing.',
    imageUri: '',
    tags: ['kale', 'chickpeas', 'avocado', 'vegan'],
    categories: ['Lunch'],
    createdAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'seed-4',
    title: 'Stuffed Potato',
    description: 'Baked potato loaded with black beans, corn, salsa, and a dollop of sour cream.',
    imageUri: '',
    tags: ['potato', 'beans', 'corn', 'salsa'],
    categories: ['Lunch'],
    createdAt: '2026-03-01T09:00:00.000Z',
  },
  {
    id: 'seed-5',
    title: 'Pasta Primavera',
    description: 'Penne pasta with sautéed seasonal vegetables in a light garlic olive oil sauce.',
    imageUri: '',
    tags: ['pasta', 'vegetables', 'garlic', 'olive oil'],
    categories: ['Dinner'],
    createdAt: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'seed-6',
    title: 'Avocado Toast',
    description: 'Sourdough toast topped with smashed avocado, cherry tomatoes, microgreens, and everything bagel seasoning.',
    imageUri: '',
    tags: ['avocado', 'bread', 'tomatoes', 'quick'],
    categories: ['Breakfast'],
    createdAt: '2026-03-01T07:00:00.000Z',
  },
  {
    id: 'seed-7',
    title: 'Trail Mix Energy Bites',
    description: 'No-bake energy balls made with oats, peanut butter, honey, chocolate chips, and dried cranberries.',
    imageUri: '',
    tags: ['oats', 'peanut butter', 'chocolate', 'snack'],
    categories: ['Snack'],
    createdAt: '2026-03-01T06:00:00.000Z',
  },
];
